### ISSUE TITLE
How to apply in span tag?

### ISSUE THREAD

**Issue by ngekoding** [amirhhashemi/tiptap-text-direction#12] opened 2023-05-04 03:55 UTC
Hi, thanks for this awesome extension.
Can you help how to apply the dir in span tag?

So, I have a content like `<span class="text-arabic">...</span>` and I want to add the dir="rtl" to it.
Currently it will wrapped with a `<p>` tag, so it make:

```html
<p dir="rtl">
  <span class="text-arabic">...</span>
</p>
```

I want make it:
```html
<span class="text-arabic" dir="rtl">...</span>
```

Thanks in advance.

**Comment by amirhhashemi** [comment] 2023-05-04 05:09
You don't need this extension to detect the direction since you already know the direction of the `span`s. You can create a custom node that selects the `span` tags that have `text-arabic` class and add `dir="rtl"` directly to them:

```typescript
import { mergeAttributes, Node } from '@tiptap/core'

const ArabicNode = Node.create({
  name: "arabic", // a unique name
  
  // You might want to give it a high priority of you have other nodes that select `span` tags
  // priority: 1000,

  group: "inline",

  content: "inline*",

  parseHTML() {
    return [
      {
        tag: "span",
        getAttrs: (node) => node.classList.contains("text-arabic"),
      },
    ];
  },

  renderHTML({ HTMLAttributes }) {
    return ["span", mergeAttributes({ dir: "rtl" }, HTMLAttributes), 0];
  },
});

// Dont' forget to register it
const editor = new Editor({
  extensions: [
    ArabicNode,
    // …
  ],
})
```
I haven't tested the above code, but you get the idea.

If you're not sure about the direction and want this extension to detect it, you can add the name of the new node ("arabic" in this case) to the `types` option:

```typescript
TextDirection.configure({
  types: ["heading", "paragraph", "arabic"],
});
```
Let me know if it works for you

**Comment by amirhhashemi** [comment] 2023-05-04 05:26
I forgot to add `inline: true`. 

I updated the code

**Comment by amirhhashemi** [comment] 2023-05-04 06:01
You should also render `class="arabic-text"` manually otherwise it would be removed from the element. I updated the code again

**Comment by ngekoding** [comment] 2023-05-04 06:19
I was try it and get nothing, the dir attribute not added.

**Comment by ngekoding** [comment] 2023-05-04 06:20
I want to implement it to this project https://github.com/ngekoding/notes-to-image, so currently I use custom extension to add the `text-arabic` class.

**Comment by ngekoding** [comment] 2023-05-04 07:03
Can you give me an official extension to follow (suggestion to learn) for this?

**Comment by amirhhashemi** [comment] 2023-05-04 07:11
It's wired because it works for me. Did you added `ArabicNode` to the list of extensions?

Can you show me your extension code so I can help you?

If you want to learn more about it you can follow the official docs: https://tiptap.dev/api/nodes

I don't know an official package that uses this technique but almost all packages has a custom node that you can use as a reference. https://github.com/ueberdosis/tiptap/tree/develop/packages

**Comment by ngekoding** [comment] 2023-05-04 07:15
Thanks for the references, I will try it again and update the info here.

I just copy your code above for the extension.

**Comment by amirhhashemi** [comment] 2023-05-04 07:18
Did you added the node to the list of extension? for example in React:
```typescript
const editor = new Editor({
  extensions: [
    ArabicNode,
    // …
  ],
})
```

**Comment by amirhhashemi** [comment] 2023-05-04 07:22
How are you adding the "text-arabic" class to the span? Without that class the code I wrote wouldn't work

**Comment by ngekoding** [comment] 2023-05-04 07:23
> Did you add the node to the list of extension? for example in React:
> 
> ```ts
> const editor = new Editor({
>   extensions: [
>     ArabicNode,
>     // …
>   ],
> })
> ```

Yes, already added it.

**Comment by ngekoding** [comment] 2023-05-04 07:24
> How are you adding the "text-arabic" class to the span? Without that class the code I wrote wouldn't work

I use a custom extension, here is the extension I use https://github.com/ngekoding/notes-to-image/blob/master/src/tiptap-extensions/text-class/text-class.js

If you have a time, you can also check the app directly to show it in action.

**Comment by ngekoding** [comment] 2023-05-04 07:38
MashaAllah, it works! and the text-arabic typed twice.

![Arabic Test](https://user-images.githubusercontent.com/11625690/236139982-53ee8b36-033d-4f07-be82-f2b536e2bb06.png)

But, how to make it in different extension?

**Comment by amirhhashemi** [comment] 2023-05-04 07:50
I think the custom node I wrote conflicts with your extension and therefor it doesn't work. Probably giving a higher priority fixes that:
```typescript
priority: 1000,
```
But since you already have an extension that selects `span`s it's easier to add `dir` directly with that.

I think the reason that `text-arabic` is added twice is that you are adding it twice, once in `renderHTML` of the `class` attribute and once in the global `renderHTML`. Removing it from the global `renderHTML` should fix that:

```typescript
  renderHTML({ HTMLAttributes }) {
    return ["span", mergeAttributes({ dir: "rtl" }, HTMLAttributes), 0];
  },
```
Also, if you are using the `text-class` extension for different purposes (maybe different classes do different things) you can do a little check before adding the `dir` attribute:
```typescript
  renderHTML({ HTMLAttributes }) {
    if (HTMLAttributes.class.includes("text-arabic")) {
      return ["span", mergeAttributes({ dir: "rtl" }, HTMLAttributes), 0];
    }
    return ["span", HTMLAttributes, 0];
  },
```

**Comment by ngekoding** [comment] 2023-05-04 08:28
> I think the custom node I wrote conflicts with your extension and therefor it doesn't work. Probably giving a higher priority fixes that:
> 
> ```ts
> const ArabicNode = Node.create({
>   priority: 1000,
>   // ...
> })
> ```

At the first of try I was already use the priority with no works.

> Also, if you are using the `text-class` extension for different purposes (maybe different classes do different things) you can do a little check before adding the `dir` attribute:

I think it is better to make a separate extension for different purpose, I will try it again.

**Comment by amirhhashemi** [comment] 2023-05-04 08:38
You extension is actually a Mark, maybe my extension should be a Mark too.
```typescritp
const ArabicMark = Mark.create({ /* ... */ })
```

**Comment by amirhhashemi** [comment] 2023-05-04 08:48
You can get more help in the TipTap discord. My extension works but somehow it conflicts with your extension. The problem is identified so probably a more experienced TipTap user knows the solution

**Comment by ngekoding** [comment] 2023-05-04 09:02
> You extension is actually a Mark, maybe my extension should be a Mark too.
> 
> ```ts
> const ArabicMark = Mark.create({ /* ... */ })
> ```

You are right, it works now but...

But I need to refresh the web page to get the updated content with `dir="rtl"`, so how can I get it automatically every time I add the `text-arabic` class?

**Comment by ngekoding** [comment] 2023-05-04 09:26
So finally I make it as you suggest, here is the code https://github.com/ngekoding/notes-to-image/commit/3423fb4a2c18c2807d6a4a36a1734e17fe32b360

Thank you very much

**Comment by amirhhashemi** [comment] 2023-05-04 09:36
Glad it fixed.

I left a message about a potential bug https://github.com/ngekoding/notes-to-image/commit/3423fb4a2c18c2807d6a4a36a1734e17fe32b360#r111766984. make sure to fix it.

I'm gonna close this issue but feel free to re-open it if you had a question.

**Closed by amirhhashemi** 2023-05-04 09:36 UTC
